# Generated by Django 3.1.2 on 2020-10-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('image', models.CharField(max_length=400)),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=800)),
                ('potDiameter', models.IntegerField()),
                ('approxHeight', models.IntegerField()),
            ],
        ),
    ]
