# Generated by Django 3.1.2 on 2020-10-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_auto_20201014_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='potDiameter',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plant',
            name='price',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
