# Generated by Django 3.1.2 on 2020-10-15 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0003_auto_20201015_1441'),
        ('plants', '0003_remove_plant_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='basket_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='basket.basket'),
            preserve_default=False,
        ),
    ]
