# Generated by Django 3.1.2 on 2020-10-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_auto_20201014_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='approxHeight',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
