# Generated by Django 3.1.2 on 2020-10-15 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0004_plant_basket_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='basket_id',
            new_name='basketID',
        ),
    ]
