# Generated by Django 3.1.2 on 2020-10-15 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0005_auto_20201015_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='basketID',
        ),
    ]
