# Generated by Django 3.1.2 on 2020-10-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_plant_customer'),
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='plant',
        ),
        migrations.AddField(
            model_name='basket',
            name='plants',
            field=models.ManyToManyField(related_name='User_orders', to='plants.Plant'),
        ),
    ]
