# Generated by Django 3.1.2 on 2020-10-15 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0003_auto_20201015_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='plants',
            new_name='plant',
        ),
    ]
