# Generated by Django 3.1.2 on 2020-10-15 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plants', '0008_auto_20201015_1518'),
        ('basket', '0004_auto_20201015_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='plant',
        ),
        migrations.AddField(
            model_name='basket',
            name='plant',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='basket_orders', to='plants.plant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='basket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
